VIRTUAL_BOX			= "boxomatic/alpine-3.20"
VERSION_BOX			= "20240704.0.1"
CPUS				= 1
MEMORY				= 1024

SCRIPT_SSH_KEY		= <<-SHELL
	if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
		echo "Création de la clef SSH de l'OS virtualisé"
		ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -q -N ""
	fi
	echo "Clef SSH créé"
	echo "Ajout de la clef SSH de HOST dans les clef SSH autorisé par l'OS virtualisé"
	cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
	rm -rf /home/vagrant/id_rsa.pub
	echo "Clef SSH de HOST ajoutée dans les clef SSH autorisé par l'OS virtualisé"
SHELL

NAME_CONTROLLER		= "jpilletS"
IP_CONTROLLER		= "192.168.56.110"

SCRIPT_VM_INIT		= <<-SHELL
	echo "Démarrage de l'instalation de K3S"
	curl -sfL https://get.k3s.io/ |  K3S_KUBECONFIG_MODE="644" K3S_TOKEN="JeSuiSUneBanane" K3S_EXTERNAL_IP="192.168.56.110" sh -s - server --flannel-iface=eth1
	echo "Fin de l'nstallation de K3S "
	echo "Début de la mise à jour du système"
#	apk update
#	apk upgrade
	echo "Fin de la mise à jour du système"
	echo "Début de l'installation de Docker"
	apk add docker
	echo "Ajout de l'utilisateur vagrant au groupe docker"
	addgroup vagrant docker
	echo "Ajout du demarage de docker lors au démarage du système"
	rc-update add docker boot
	echo "Fin de l'installation de Docker"
SHELL

SCRIPT_VM_REBOOT	= <<-SHELL
	echo "Redémarrage de la VM"
	reboot
SHELL

SCRIPT_WAIT_FOR_SSH = <<-SHELL
	echo "Attente de la disponibilité du service SSH"
	while ! nc -z 192.168.56.110 22; do
		sleep 1
	done
	echo "SSH disponible"
SHELL

SCRIPT_DK_STATUS	= <<-SHELL
	echo "Demarrage de Docker"
	while docker info > /dev/null 2>&1; do
		sleep 1
	done
	echo "Docker prêt"
	docker version
	docker info
SHELL


Vagrant.configure("2") do |config|
	config.vm.box				= VIRTUAL_BOX
  	config.vm.box_version		= VERSION_BOX

	config.vm.provider :virtualbox do |vb|
		vb.cpus					= CPUS
		vb.memory				= MEMORY
		vb.name					= NAME_CONTROLLER
	end

	config.vm.define "jpilletS" do |jpilletS|
		# Configuration commune clef SSH
		jpilletS.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"
		jpilletS.vm.provision "shell", inline: SCRIPT_SSH_KEY

		jpilletS.vm.hostname	= NAME_CONTROLLER
		jpilletS.vm.network "private_network", ip: IP_CONTROLLER

		jpilletS.vm.provision "shell", inline: SCRIPT_VM_INIT

		jpilletS.vm.provision "shell", inline: SCRIPT_VM_REBOOT

		jpilletS.vm.provision "shell", inline: SCRIPT_WAIT_FOR_SSH, run: "always"

		jpilletS.vm.provision "shell", inline: SCRIPT_DK_STATUS, run: "always"
	end
end
