VIRTUAL_BOX			= "boxomatic/alpine-3.20"
VERSION_BOX			= "20240704.0.1"
CPUS				= 1
MEMORY				= 2048

SCRIPT_SSH_KEY		= <<-SHELL
	if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
		echo "Création de la clef SSH de l'OS virtualisé"
		ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -q -N ""
	fi
	echo "Clef SSH créé"
	echo "Ajout de la clef SSH de HOST dans les clef SSH autorisé par l'OS virtualisé"
	cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
	rm -rf /home/vagrant/id_rsa.pub
	echo "Clef SSH de HOST ajoutée dans les clef SSH autorisé par l'OS virtualisé"
SHELL

NAME_GUEST			= "jpilletS"
IP_GUEST			= "192.168.56.110"
PORT_HOST			= 2222
PORT_GUEST			= 2222

SCRIPT_VM_INIT		= <<-SHELL
	echo "Démarrage de l'instalation de K3S"
	curl -sfL https://get.k3s.io/ | K3S_KUBECONFIG_MODE="644" K3S_TOKEN="JeSuiSUneBanane" K3S_EXTERNAL_IP="192.168.56.110" sh -s - server --flannel-iface=eth1
	echo "Fin de l'installation de K3S "
SHELL


Vagrant.configure("2") do |config|
	config.vm.box				= VIRTUAL_BOX
  	config.vm.box_version		= VERSION_BOX

	config.vm.provider :virtualbox do |vb|
		vb.cpus					= CPUS
		vb.memory				= MEMORY
		vb.name					= NAME_GUEST
	end

	# Configuration commune clef SSH
	config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"
	config.vm.provision "shell", inline: SCRIPT_SSH_KEY

	config.vm.define "jpilletS" do |jpilletS|
		jpilletS.vm.hostname	= NAME_GUEST
		jpilletS.vm.network "private_network", ip: IP_GUEST
#		jpilletS.vm.network "forwarded_port", id: "ssh", host: PORT_HOST, guest: PORT_GUEST
		jpilletS.vm.provision "shell", inline: SCRIPT_VM_INIT
	end
end
