Vagrant.configure("2") do |config|
	config.vm.box = "boxomatic/alpine-3.20"
	config.vm.box_version = "20240704.0.1"

	config.vm.define "jpilletS" do |jpilletS|
	  jpilletS.vm.hostname = "jpilletS"
	  jpilletS.vm.network "private_network", ip: "192.168.56.110"
	  jpilletS.vm.provider :virtualbox do |vbs|
		vbs.name = "jpilletS"
		vbs.cpus = 1
		vbs.memory = 1024
	  end
  
	  # Générer une clé SSH pour l'utilisateur vagrant s'il n'y en a pas déjà une
	  jpilletS.vm.provision "shell", inline: <<-SHELL
		if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
		   ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -q -N ""
		fi
	  SHELL
  
	  # Copier la clé publique locale dans la VM
	  jpilletS.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"
  
	  # Ajouter la clé publique au fichier authorized_keys de l'utilisateur jpilletS
	  jpilletS.vm.provision "shell", inline: <<-SHELL
		cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
		rm -rf /home/vagrant/id_rsa.pub

		apk update && apk upgrade
		curl -sfL https://get.k3s.io/ | K3S_KUBECONFIG_MODE="644" K3S_TOKEN="JeSuiSUneBanane" K3S_EXTERNAL_IP="192.168.56.110" sh -s -
	  SHELL
	end
end
