Vagrant.configure("2") do |config|
	config.vm.box = "alvistack/ubuntu-24.04"
  
	config.vm.define "jpilletS" do |jpilletS|
	  jpilletS.vm.hostname = "jpilletS"
	  jpilletS.vm.network "private_network", ip: "192.168.56.110"
	  jpilletS.vm.provider :virtualbox do |vbs|
		vbs.name = "jpilletS"
		vbs.cpus = 1
		vbs.memory = 512
	  end
  
#	  jpilletS.ssh.username = 'jpilletS'
#	  jpilletS.ssh.username = 'jpilletSP'
#	  jpilletS.ssh.insert_key = false
  
	  # Générer une clé SSH pour l'utilisateur vagrant s'il n'y en a pas déjà une
	  jpilletS.vm.provision "shell", inline: <<-SHELL
		if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
		  ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -q -N ""
		fi
	  SHELL
  
	  # Copier la clé publique locale dans la VM
	  jpilletS.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"
  
	  # Ajouter la clé publique au fichier authorized_keys de l'utilisateur jpilletS
	  jpilletS.vm.provision "shell", inline: <<-SHELL
		mkdir -p /home/vagrant/.ssh
		cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
#		chmod 600 /home/vagrant/.ssh/authorized_keys
#		chown -R jpilletS:jpilletS /home/jpilletS/.ssh
#		rm /tmp/id_rsa.pub
	  SHELL
	end
end
#  config.vm.define "jpilletSW" do |jpilletSW|
#    jpilletSW.vm.hostname = "jpilletSW"
#    jpilletSW.vm.network "private_network", ip: "192.168.56.111"
#    jpilletSW.vm.provider :virtualbox do |vbsw|
#      vbsw.name = "jpilletSW"
#	  vbsw.cpus = 1
#	  vbsw.memory = 512
#    end
#	jpilletSW.ssh.username = 'jpilletSW'
#	jpilletSW.ssh.password = 'jpilletSWP'
#	jpilletSW.ssh.insert_key = false
#  end
#end
